import { Injectable } from '@nestjs/common';
import PDFDocument = require('pdfkit');
import { PassThrough } from 'stream';

interface WaybillPdfData {
  waybillNumber: string;
  sealNumber?: string | null;
  productsSummary?: string | null;
  receiverName?: string | null;
  receiverPhone?: string | null;
  signedByName?: string | null;
  signedAt?: Date | null;
  createdAt: Date;
  companyName: string;
  orderNumber: string;
  pickupLocation: string;
  destinationLocation: string;
  vehiclePlate: string;
  driverName: string;
}

@Injectable()
export class PdfService {
  generateWaybillPdf(data: WaybillPdfData): PassThrough {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const stream = new PassThrough();
    doc.pipe(stream);

    doc
      .fontSize(20)
      .fillColor('#1F4E79')
      .text(data.companyName, { align: 'left' })
      .fontSize(10)
      .fillColor('#555555')
      .text('Waybill / Delivery Note', { align: 'left' })
      .moveDown(1.5);

    doc
      .fontSize(14)
      .fillColor('#000000')
      .text(`Waybill No: ${data.waybillNumber}`, { continued: false })
      .fontSize(10)
      .fillColor('#555555')
      .text(`Order Reference: ${data.orderNumber}`)
      .text(`Issued: ${data.createdAt.toLocaleDateString()}`)
      .moveDown(1);

    this.drawSectionHeader(doc, 'Route');
    this.drawRow(doc, 'Pickup', data.pickupLocation);
    this.drawRow(doc, 'Destination', data.destinationLocation);
    doc.moveDown(0.5);

    this.drawSectionHeader(doc, 'Assignment');
    this.drawRow(doc, 'Vehicle', data.vehiclePlate);
    this.drawRow(doc, 'Driver', data.driverName);
    if (data.sealNumber) this.drawRow(doc, 'Seal Number', data.sealNumber);
    if (data.productsSummary) this.drawRow(doc, 'Products', data.productsSummary);
    doc.moveDown(0.5);

    if (data.signedAt) {
      this.drawSectionHeader(doc, 'Proof of Delivery');
      this.drawRow(doc, 'Received By', data.receiverName ?? '—');
      if (data.receiverPhone) this.drawRow(doc, 'Receiver Phone', data.receiverPhone);
      this.drawRow(doc, 'Signed By', data.signedByName ?? '—');
      this.drawRow(doc, 'Signed At', data.signedAt.toLocaleString());
    } else {
      doc.fontSize(10).fillColor('#999999').text('Proof of delivery not yet recorded.');
    }

    doc
      .moveDown(3)
      .fontSize(8)
      .fillColor('#AAAAAA')
      .text('Generated by Fleet Ops — this document is system-generated and does not require a physical signature to be valid unless otherwise required by the receiving party.', {
        align: 'left',
      });

    doc.end();
    return stream;
  }

  private drawSectionHeader(doc: PDFKit.PDFDocument, text: string) {
    doc.fontSize(12).fillColor('#1F4E79').text(text).moveDown(0.3);
  }

  private drawRow(doc: PDFKit.PDFDocument, label: string, value: string) {
    doc
      .fontSize(10)
      .fillColor('#555555')
      .text(label, { continued: true, width: 120 })
      .fillColor('#000000')
      .text(`  ${value}`);
  }
}
